/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package battleship-0.1.0 */
#ifndef VERSION_battleship
#define VERSION_battleship "0.1.0"
#endif /* VERSION_battleship */
#ifndef MIN_VERSION_battleship
#define MIN_VERSION_battleship(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_battleship */
/* package aeson-2.2.3.0 */
#ifndef VERSION_aeson
#define VERSION_aeson "2.2.3.0"
#endif /* VERSION_aeson */
#ifndef MIN_VERSION_aeson
#define MIN_VERSION_aeson(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 3)
#endif /* MIN_VERSION_aeson */
/* package async-2.2.5 */
#ifndef VERSION_async
#define VERSION_async "2.2.5"
#endif /* VERSION_async */
#ifndef MIN_VERSION_async
#define MIN_VERSION_async(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 5)
#endif /* MIN_VERSION_async */
/* package base-4.20.2.0 */
#ifndef VERSION_base
#define VERSION_base "4.20.2.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  20 || \
  (major1) == 4 && (major2) == 20 && (minor) <= 2)
#endif /* MIN_VERSION_base */
/* package base64-bytestring-1.2.1.0 */
#ifndef VERSION_base64_bytestring
#define VERSION_base64_bytestring "1.2.1.0"
#endif /* VERSION_base64_bytestring */
#ifndef MIN_VERSION_base64_bytestring
#define MIN_VERSION_base64_bytestring(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 1)
#endif /* MIN_VERSION_base64_bytestring */
/* package bytestring-0.12.2.0 */
#ifndef VERSION_bytestring
#define VERSION_bytestring "0.12.2.0"
#endif /* VERSION_bytestring */
#ifndef MIN_VERSION_bytestring
#define MIN_VERSION_bytestring(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  12 || \
  (major1) == 0 && (major2) == 12 && (minor) <= 2)
#endif /* MIN_VERSION_bytestring */
/* package containers-0.7 */
#ifndef VERSION_containers
#define VERSION_containers "0.7"
#endif /* VERSION_containers */
#ifndef MIN_VERSION_containers
#define MIN_VERSION_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  7 || \
  (major1) == 0 && (major2) == 7 && (minor) <= 0)
#endif /* MIN_VERSION_containers */
/* package cryptonite-0.30 */
#ifndef VERSION_cryptonite
#define VERSION_cryptonite "0.30"
#endif /* VERSION_cryptonite */
#ifndef MIN_VERSION_cryptonite
#define MIN_VERSION_cryptonite(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  30 || \
  (major1) == 0 && (major2) == 30 && (minor) <= 0)
#endif /* MIN_VERSION_cryptonite */
/* package directory-1.3.8.5 */
#ifndef VERSION_directory
#define VERSION_directory "1.3.8.5"
#endif /* VERSION_directory */
#ifndef MIN_VERSION_directory
#define MIN_VERSION_directory(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 8)
#endif /* MIN_VERSION_directory */
/* package dotenv-0.12.0.0 */
#ifndef VERSION_dotenv
#define VERSION_dotenv "0.12.0.0"
#endif /* VERSION_dotenv */
#ifndef MIN_VERSION_dotenv
#define MIN_VERSION_dotenv(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  12 || \
  (major1) == 0 && (major2) == 12 && (minor) <= 0)
#endif /* MIN_VERSION_dotenv */
/* package filepath-1.5.4.0 */
#ifndef VERSION_filepath
#define VERSION_filepath "1.5.4.0"
#endif /* VERSION_filepath */
#ifndef MIN_VERSION_filepath
#define MIN_VERSION_filepath(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  5 || \
  (major1) == 1 && (major2) == 5 && (minor) <= 4)
#endif /* MIN_VERSION_filepath */
/* package mtl-2.3.1 */
#ifndef VERSION_mtl
#define VERSION_mtl "2.3.1"
#endif /* VERSION_mtl */
#ifndef MIN_VERSION_mtl
#define MIN_VERSION_mtl(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  3 || \
  (major1) == 2 && (major2) == 3 && (minor) <= 1)
#endif /* MIN_VERSION_mtl */
/* package network-3.2.8.0 */
#ifndef VERSION_network
#define VERSION_network "3.2.8.0"
#endif /* VERSION_network */
#ifndef MIN_VERSION_network
#define MIN_VERSION_network(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  2 || \
  (major1) == 3 && (major2) == 2 && (minor) <= 8)
#endif /* MIN_VERSION_network */
/* package postgresql-simple-0.7.0.1 */
#ifndef VERSION_postgresql_simple
#define VERSION_postgresql_simple "0.7.0.1"
#endif /* VERSION_postgresql_simple */
#ifndef MIN_VERSION_postgresql_simple
#define MIN_VERSION_postgresql_simple(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  7 || \
  (major1) == 0 && (major2) == 7 && (minor) <= 0)
#endif /* MIN_VERSION_postgresql_simple */
/* package random-1.2.1.3 */
#ifndef VERSION_random
#define VERSION_random "1.2.1.3"
#endif /* VERSION_random */
#ifndef MIN_VERSION_random
#define MIN_VERSION_random(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 1)
#endif /* MIN_VERSION_random */
/* package stm-2.5.3.1 */
#ifndef VERSION_stm
#define VERSION_stm "2.5.3.1"
#endif /* VERSION_stm */
#ifndef MIN_VERSION_stm
#define MIN_VERSION_stm(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  5 || \
  (major1) == 2 && (major2) == 5 && (minor) <= 3)
#endif /* MIN_VERSION_stm */
/* package text-2.1.3 */
#ifndef VERSION_text
#define VERSION_text "2.1.3"
#endif /* VERSION_text */
#ifndef MIN_VERSION_text
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  1 || \
  (major1) == 2 && (major2) == 1 && (minor) <= 3)
#endif /* MIN_VERSION_text */
/* package threepenny-gui-0.9.4.2 */
#ifndef VERSION_threepenny_gui
#define VERSION_threepenny_gui "0.9.4.2"
#endif /* VERSION_threepenny_gui */
#ifndef MIN_VERSION_threepenny_gui
#define MIN_VERSION_threepenny_gui(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  9 || \
  (major1) == 0 && (major2) == 9 && (minor) <= 4)
#endif /* MIN_VERSION_threepenny_gui */
/* package transformers-0.6.1.1 */
#ifndef VERSION_transformers
#define VERSION_transformers "0.6.1.1"
#endif /* VERSION_transformers */
#ifndef MIN_VERSION_transformers
#define MIN_VERSION_transformers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 1)
#endif /* MIN_VERSION_transformers */

/* tool gcc-14.0.6 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "14.0.6"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  14 || \
  (major1) == 14 && (major2) <  0 || \
  (major1) == 14 && (major2) == 0 && (minor) <= 6)
#endif /* MIN_TOOL_VERSION_gcc */
/* tool ghc-9.10.3 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "9.10.3"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  10 || \
  (major1) == 9 && (major2) == 10 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_ghc */
/* tool ghc-pkg-9.10.3 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "9.10.3"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  10 || \
  (major1) == 9 && (major2) == 10 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_ghc_pkg */
/* tool haddock-2.31.1 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.31.1"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  31 || \
  (major1) == 2 && (major2) == 31 && (minor) <= 1)
#endif /* MIN_TOOL_VERSION_haddock */
/* tool hpc-0.69 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.69"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  69 || \
  (major1) == 0 && (major2) == 69 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */
/* tool hsc2hs-0.68.10 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.10"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 10)
#endif /* MIN_TOOL_VERSION_hsc2hs */
/* tool runghc-9.10.3 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "9.10.3"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  10 || \
  (major1) == 9 && (major2) == 10 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_runghc */

#ifndef CURRENT_PACKAGE_KEY
#define CURRENT_PACKAGE_KEY "battleship-0.1.0-Brv4rfCBFgoHRtWx0gC062"
#endif /* CURRENT_packageKey */
#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "battleship-0.1.0-Brv4rfCBFgoHRtWx0gC062"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.1.0"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package battleship-0.1.0 */
#ifndef VERSION_battleship
#define VERSION_battleship "0.1.0"
#endif /* VERSION_battleship */
#ifndef MIN_VERSION_battleship
#define MIN_VERSION_battleship(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_battleship */
/* package aeson-2.2.3.0 */
#ifndef VERSION_aeson
#define VERSION_aeson "2.2.3.0"
#endif /* VERSION_aeson */
#ifndef MIN_VERSION_aeson
#define MIN_VERSION_aeson(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 3)
#endif /* MIN_VERSION_aeson */
/* package async-2.2.5 */
#ifndef VERSION_async
#define VERSION_async "2.2.5"
#endif /* VERSION_async */
#ifndef MIN_VERSION_async
#define MIN_VERSION_async(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 5)
#endif /* MIN_VERSION_async */
/* package base-4.20.2.0 */
#ifndef VERSION_base
#define VERSION_base "4.20.2.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  20 || \
  (major1) == 4 && (major2) == 20 && (minor) <= 2)
#endif /* MIN_VERSION_base */
/* package base64-bytestring-1.2.1.0 */
#ifndef VERSION_base64_bytestring
#define VERSION_base64_bytestring "1.2.1.0"
#endif /* VERSION_base64_bytestring */
#ifndef MIN_VERSION_base64_bytestring
#define MIN_VERSION_base64_bytestring(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 1)
#endif /* MIN_VERSION_base64_bytestring */
/* package battleship-0.1.0 */
#ifndef VERSION_battleship
#define VERSION_battleship "0.1.0"
#endif /* VERSION_battleship */
#ifndef MIN_VERSION_battleship
#define MIN_VERSION_battleship(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_battleship */
/* package bytestring-0.12.2.0 */
#ifndef VERSION_bytestring
#define VERSION_bytestring "0.12.2.0"
#endif /* VERSION_bytestring */
#ifndef MIN_VERSION_bytestring
#define MIN_VERSION_bytestring(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  12 || \
  (major1) == 0 && (major2) == 12 && (minor) <= 2)
#endif /* MIN_VERSION_bytestring */
/* package containers-0.7 */
#ifndef VERSION_containers
#define VERSION_containers "0.7"
#endif /* VERSION_containers */
#ifndef MIN_VERSION_containers
#define MIN_VERSION_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  7 || \
  (major1) == 0 && (major2) == 7 && (minor) <= 0)
#endif /* MIN_VERSION_containers */
/* package cryptonite-0.30 */
#ifndef VERSION_cryptonite
#define VERSION_cryptonite "0.30"
#endif /* VERSION_cryptonite */
#ifndef MIN_VERSION_cryptonite
#define MIN_VERSION_cryptonite(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  30 || \
  (major1) == 0 && (major2) == 30 && (minor) <= 0)
#endif /* MIN_VERSION_cryptonite */
/* package directory-1.3.8.5 */
#ifndef VERSION_directory
#define VERSION_directory "1.3.8.5"
#endif /* VERSION_directory */
#ifndef MIN_VERSION_directory
#define MIN_VERSION_directory(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 8)
#endif /* MIN_VERSION_directory */
/* package dotenv-0.12.0.0 */
#ifndef VERSION_dotenv
#define VERSION_dotenv "0.12.0.0"
#endif /* VERSION_dotenv */
#ifndef MIN_VERSION_dotenv
#define MIN_VERSION_dotenv(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  12 || \
  (major1) == 0 && (major2) == 12 && (minor) <= 0)
#endif /* MIN_VERSION_dotenv */
/* package filepath-1.5.4.0 */
#ifndef VERSION_filepath
#define VERSION_filepath "1.5.4.0"
#endif /* VERSION_filepath */
#ifndef MIN_VERSION_filepath
#define MIN_VERSION_filepath(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  5 || \
  (major1) == 1 && (major2) == 5 && (minor) <= 4)
#endif /* MIN_VERSION_filepath */
/* package mtl-2.3.1 */
#ifndef VERSION_mtl
#define VERSION_mtl "2.3.1"
#endif /* VERSION_mtl */
#ifndef MIN_VERSION_mtl
#define MIN_VERSION_mtl(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  3 || \
  (major1) == 2 && (major2) == 3 && (minor) <= 1)
#endif /* MIN_VERSION_mtl */
/* package network-3.2.8.0 */
#ifndef VERSION_network
#define VERSION_network "3.2.8.0"
#endif /* VERSION_network */
#ifndef MIN_VERSION_network
#define MIN_VERSION_network(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  2 || \
  (major1) == 3 && (major2) == 2 && (minor) <= 8)
#endif /* MIN_VERSION_network */
/* package postgresql-simple-0.7.0.1 */
#ifndef VERSION_postgresql_simple
#define VERSION_postgresql_simple "0.7.0.1"
#endif /* VERSION_postgresql_simple */
#ifndef MIN_VERSION_postgresql_simple
#define MIN_VERSION_postgresql_simple(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  7 || \
  (major1) == 0 && (major2) == 7 && (minor) <= 0)
#endif /* MIN_VERSION_postgresql_simple */
/* package random-1.2.1.3 */
#ifndef VERSION_random
#define VERSION_random "1.2.1.3"
#endif /* VERSION_random */
#ifndef MIN_VERSION_random
#define MIN_VERSION_random(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 1)
#endif /* MIN_VERSION_random */
/* package stm-2.5.3.1 */
#ifndef VERSION_stm
#define VERSION_stm "2.5.3.1"
#endif /* VERSION_stm */
#ifndef MIN_VERSION_stm
#define MIN_VERSION_stm(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  5 || \
  (major1) == 2 && (major2) == 5 && (minor) <= 3)
#endif /* MIN_VERSION_stm */
/* package text-2.1.3 */
#ifndef VERSION_text
#define VERSION_text "2.1.3"
#endif /* VERSION_text */
#ifndef MIN_VERSION_text
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  1 || \
  (major1) == 2 && (major2) == 1 && (minor) <= 3)
#endif /* MIN_VERSION_text */
/* package threepenny-gui-0.9.4.2 */
#ifndef VERSION_threepenny_gui
#define VERSION_threepenny_gui "0.9.4.2"
#endif /* VERSION_threepenny_gui */
#ifndef MIN_VERSION_threepenny_gui
#define MIN_VERSION_threepenny_gui(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  9 || \
  (major1) == 0 && (major2) == 9 && (minor) <= 4)
#endif /* MIN_VERSION_threepenny_gui */
/* package transformers-0.6.1.1 */
#ifndef VERSION_transformers
#define VERSION_transformers "0.6.1.1"
#endif /* VERSION_transformers */
#ifndef MIN_VERSION_transformers
#define MIN_VERSION_transformers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 1)
#endif /* MIN_VERSION_transformers */

/* tool gcc-14.0.6 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "14.0.6"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  14 || \
  (major1) == 14 && (major2) <  0 || \
  (major1) == 14 && (major2) == 0 && (minor) <= 6)
#endif /* MIN_TOOL_VERSION_gcc */
/* tool ghc-9.10.3 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "9.10.3"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  10 || \
  (major1) == 9 && (major2) == 10 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_ghc */
/* tool ghc-pkg-9.10.3 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "9.10.3"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  10 || \
  (major1) == 9 && (major2) == 10 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_ghc_pkg */
/* tool haddock-2.31.1 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.31.1"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  31 || \
  (major1) == 2 && (major2) == 31 && (minor) <= 1)
#endif /* MIN_TOOL_VERSION_haddock */
/* tool hpc-0.69 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.69"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  69 || \
  (major1) == 0 && (major2) == 69 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */
/* tool hsc2hs-0.68.10 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.10"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 10)
#endif /* MIN_TOOL_VERSION_hsc2hs */
/* tool runghc-9.10.3 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "9.10.3"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  10 || \
  (major1) == 9 && (major2) == 10 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_runghc */

#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "battleship-0.1.0-Cgxe7XwhIDkIYCzpof2Up6-battleship-client"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.1.0"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package battleship-0.1.0 */
#ifndef VERSION_battleship
#define VERSION_battleship "0.1.0"
#endif /* VERSION_battleship */
#ifndef MIN_VERSION_battleship
#define MIN_VERSION_battleship(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_battleship */
/* package aeson-2.2.3.0 */
#ifndef VERSION_aeson
#define VERSION_aeson "2.2.3.0"
#endif /* VERSION_aeson */
#ifndef MIN_VERSION_aeson
#define MIN_VERSION_aeson(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 3)
#endif /* MIN_VERSION_aeson */
/* package async-2.2.5 */
#ifndef VERSION_async
#define VERSION_async "2.2.5"
#endif /* VERSION_async */
#ifndef MIN_VERSION_async
#define MIN_VERSION_async(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 5)
#endif /* MIN_VERSION_async */
/* package base-4.20.2.0 */
#ifndef VERSION_base
#define VERSION_base "4.20.2.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  20 || \
  (major1) == 4 && (major2) == 20 && (minor) <= 2)
#endif /* MIN_VERSION_base */
/* package base64-bytestring-1.2.1.0 */
#ifndef VERSION_base64_bytestring
#define VERSION_base64_bytestring "1.2.1.0"
#endif /* VERSION_base64_bytestring */
#ifndef MIN_VERSION_base64_bytestring
#define MIN_VERSION_base64_bytestring(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 1)
#endif /* MIN_VERSION_base64_bytestring */
/* package battleship-0.1.0 */
#ifndef VERSION_battleship
#define VERSION_battleship "0.1.0"
#endif /* VERSION_battleship */
#ifndef MIN_VERSION_battleship
#define MIN_VERSION_battleship(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_battleship */
/* package bytestring-0.12.2.0 */
#ifndef VERSION_bytestring
#define VERSION_bytestring "0.12.2.0"
#endif /* VERSION_bytestring */
#ifndef MIN_VERSION_bytestring
#define MIN_VERSION_bytestring(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  12 || \
  (major1) == 0 && (major2) == 12 && (minor) <= 2)
#endif /* MIN_VERSION_bytestring */
/* package containers-0.7 */
#ifndef VERSION_containers
#define VERSION_containers "0.7"
#endif /* VERSION_containers */
#ifndef MIN_VERSION_containers
#define MIN_VERSION_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  7 || \
  (major1) == 0 && (major2) == 7 && (minor) <= 0)
#endif /* MIN_VERSION_containers */
/* package cryptonite-0.30 */
#ifndef VERSION_cryptonite
#define VERSION_cryptonite "0.30"
#endif /* VERSION_cryptonite */
#ifndef MIN_VERSION_cryptonite
#define MIN_VERSION_cryptonite(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  30 || \
  (major1) == 0 && (major2) == 30 && (minor) <= 0)
#endif /* MIN_VERSION_cryptonite */
/* package directory-1.3.8.5 */
#ifndef VERSION_directory
#define VERSION_directory "1.3.8.5"
#endif /* VERSION_directory */
#ifndef MIN_VERSION_directory
#define MIN_VERSION_directory(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 8)
#endif /* MIN_VERSION_directory */
/* package dotenv-0.12.0.0 */
#ifndef VERSION_dotenv
#define VERSION_dotenv "0.12.0.0"
#endif /* VERSION_dotenv */
#ifndef MIN_VERSION_dotenv
#define MIN_VERSION_dotenv(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  12 || \
  (major1) == 0 && (major2) == 12 && (minor) <= 0)
#endif /* MIN_VERSION_dotenv */
/* package filepath-1.5.4.0 */
#ifndef VERSION_filepath
#define VERSION_filepath "1.5.4.0"
#endif /* VERSION_filepath */
#ifndef MIN_VERSION_filepath
#define MIN_VERSION_filepath(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  5 || \
  (major1) == 1 && (major2) == 5 && (minor) <= 4)
#endif /* MIN_VERSION_filepath */
/* package mtl-2.3.1 */
#ifndef VERSION_mtl
#define VERSION_mtl "2.3.1"
#endif /* VERSION_mtl */
#ifndef MIN_VERSION_mtl
#define MIN_VERSION_mtl(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  3 || \
  (major1) == 2 && (major2) == 3 && (minor) <= 1)
#endif /* MIN_VERSION_mtl */
/* package network-3.2.8.0 */
#ifndef VERSION_network
#define VERSION_network "3.2.8.0"
#endif /* VERSION_network */
#ifndef MIN_VERSION_network
#define MIN_VERSION_network(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  2 || \
  (major1) == 3 && (major2) == 2 && (minor) <= 8)
#endif /* MIN_VERSION_network */
/* package postgresql-simple-0.7.0.1 */
#ifndef VERSION_postgresql_simple
#define VERSION_postgresql_simple "0.7.0.1"
#endif /* VERSION_postgresql_simple */
#ifndef MIN_VERSION_postgresql_simple
#define MIN_VERSION_postgresql_simple(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  7 || \
  (major1) == 0 && (major2) == 7 && (minor) <= 0)
#endif /* MIN_VERSION_postgresql_simple */
/* package random-1.2.1.3 */
#ifndef VERSION_random
#define VERSION_random "1.2.1.3"
#endif /* VERSION_random */
#ifndef MIN_VERSION_random
#define MIN_VERSION_random(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 1)
#endif /* MIN_VERSION_random */
/* package stm-2.5.3.1 */
#ifndef VERSION_stm
#define VERSION_stm "2.5.3.1"
#endif /* VERSION_stm */
#ifndef MIN_VERSION_stm
#define MIN_VERSION_stm(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  5 || \
  (major1) == 2 && (major2) == 5 && (minor) <= 3)
#endif /* MIN_VERSION_stm */
/* package text-2.1.3 */
#ifndef VERSION_text
#define VERSION_text "2.1.3"
#endif /* VERSION_text */
#ifndef MIN_VERSION_text
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  1 || \
  (major1) == 2 && (major2) == 1 && (minor) <= 3)
#endif /* MIN_VERSION_text */
/* package threepenny-gui-0.9.4.2 */
#ifndef VERSION_threepenny_gui
#define VERSION_threepenny_gui "0.9.4.2"
#endif /* VERSION_threepenny_gui */
#ifndef MIN_VERSION_threepenny_gui
#define MIN_VERSION_threepenny_gui(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  9 || \
  (major1) == 0 && (major2) == 9 && (minor) <= 4)
#endif /* MIN_VERSION_threepenny_gui */
/* package transformers-0.6.1.1 */
#ifndef VERSION_transformers
#define VERSION_transformers "0.6.1.1"
#endif /* VERSION_transformers */
#ifndef MIN_VERSION_transformers
#define MIN_VERSION_transformers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 1)
#endif /* MIN_VERSION_transformers */

/* tool gcc-14.0.6 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "14.0.6"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  14 || \
  (major1) == 14 && (major2) <  0 || \
  (major1) == 14 && (major2) == 0 && (minor) <= 6)
#endif /* MIN_TOOL_VERSION_gcc */
/* tool ghc-9.10.3 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "9.10.3"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  10 || \
  (major1) == 9 && (major2) == 10 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_ghc */
/* tool ghc-pkg-9.10.3 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "9.10.3"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  10 || \
  (major1) == 9 && (major2) == 10 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_ghc_pkg */
/* tool haddock-2.31.1 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.31.1"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  31 || \
  (major1) == 2 && (major2) == 31 && (minor) <= 1)
#endif /* MIN_TOOL_VERSION_haddock */
/* tool hpc-0.69 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.69"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  69 || \
  (major1) == 0 && (major2) == 69 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */
/* tool hsc2hs-0.68.10 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.10"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 10)
#endif /* MIN_TOOL_VERSION_hsc2hs */
/* tool runghc-9.10.3 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "9.10.3"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  10 || \
  (major1) == 9 && (major2) == 10 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_runghc */

#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "battleship-0.1.0-FuoSfBtC8NZJpsRIosC6OD-battleship-gui"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.1.0"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package battleship-0.1.0 */
#ifndef VERSION_battleship
#define VERSION_battleship "0.1.0"
#endif /* VERSION_battleship */
#ifndef MIN_VERSION_battleship
#define MIN_VERSION_battleship(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_battleship */
/* package aeson-2.2.3.0 */
#ifndef VERSION_aeson
#define VERSION_aeson "2.2.3.0"
#endif /* VERSION_aeson */
#ifndef MIN_VERSION_aeson
#define MIN_VERSION_aeson(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 3)
#endif /* MIN_VERSION_aeson */
/* package async-2.2.5 */
#ifndef VERSION_async
#define VERSION_async "2.2.5"
#endif /* VERSION_async */
#ifndef MIN_VERSION_async
#define MIN_VERSION_async(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 5)
#endif /* MIN_VERSION_async */
/* package base-4.20.2.0 */
#ifndef VERSION_base
#define VERSION_base "4.20.2.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  20 || \
  (major1) == 4 && (major2) == 20 && (minor) <= 2)
#endif /* MIN_VERSION_base */
/* package base64-bytestring-1.2.1.0 */
#ifndef VERSION_base64_bytestring
#define VERSION_base64_bytestring "1.2.1.0"
#endif /* VERSION_base64_bytestring */
#ifndef MIN_VERSION_base64_bytestring
#define MIN_VERSION_base64_bytestring(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 1)
#endif /* MIN_VERSION_base64_bytestring */
/* package battleship-0.1.0 */
#ifndef VERSION_battleship
#define VERSION_battleship "0.1.0"
#endif /* VERSION_battleship */
#ifndef MIN_VERSION_battleship
#define MIN_VERSION_battleship(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_battleship */
/* package bytestring-0.12.2.0 */
#ifndef VERSION_bytestring
#define VERSION_bytestring "0.12.2.0"
#endif /* VERSION_bytestring */
#ifndef MIN_VERSION_bytestring
#define MIN_VERSION_bytestring(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  12 || \
  (major1) == 0 && (major2) == 12 && (minor) <= 2)
#endif /* MIN_VERSION_bytestring */
/* package containers-0.7 */
#ifndef VERSION_containers
#define VERSION_containers "0.7"
#endif /* VERSION_containers */
#ifndef MIN_VERSION_containers
#define MIN_VERSION_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  7 || \
  (major1) == 0 && (major2) == 7 && (minor) <= 0)
#endif /* MIN_VERSION_containers */
/* package cryptonite-0.30 */
#ifndef VERSION_cryptonite
#define VERSION_cryptonite "0.30"
#endif /* VERSION_cryptonite */
#ifndef MIN_VERSION_cryptonite
#define MIN_VERSION_cryptonite(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  30 || \
  (major1) == 0 && (major2) == 30 && (minor) <= 0)
#endif /* MIN_VERSION_cryptonite */
/* package directory-1.3.8.5 */
#ifndef VERSION_directory
#define VERSION_directory "1.3.8.5"
#endif /* VERSION_directory */
#ifndef MIN_VERSION_directory
#define MIN_VERSION_directory(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 8)
#endif /* MIN_VERSION_directory */
/* package dotenv-0.12.0.0 */
#ifndef VERSION_dotenv
#define VERSION_dotenv "0.12.0.0"
#endif /* VERSION_dotenv */
#ifndef MIN_VERSION_dotenv
#define MIN_VERSION_dotenv(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  12 || \
  (major1) == 0 && (major2) == 12 && (minor) <= 0)
#endif /* MIN_VERSION_dotenv */
/* package filepath-1.5.4.0 */
#ifndef VERSION_filepath
#define VERSION_filepath "1.5.4.0"
#endif /* VERSION_filepath */
#ifndef MIN_VERSION_filepath
#define MIN_VERSION_filepath(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  5 || \
  (major1) == 1 && (major2) == 5 && (minor) <= 4)
#endif /* MIN_VERSION_filepath */
/* package mtl-2.3.1 */
#ifndef VERSION_mtl
#define VERSION_mtl "2.3.1"
#endif /* VERSION_mtl */
#ifndef MIN_VERSION_mtl
#define MIN_VERSION_mtl(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  3 || \
  (major1) == 2 && (major2) == 3 && (minor) <= 1)
#endif /* MIN_VERSION_mtl */
/* package network-3.2.8.0 */
#ifndef VERSION_network
#define VERSION_network "3.2.8.0"
#endif /* VERSION_network */
#ifndef MIN_VERSION_network
#define MIN_VERSION_network(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  2 || \
  (major1) == 3 && (major2) == 2 && (minor) <= 8)
#endif /* MIN_VERSION_network */
/* package postgresql-simple-0.7.0.1 */
#ifndef VERSION_postgresql_simple
#define VERSION_postgresql_simple "0.7.0.1"
#endif /* VERSION_postgresql_simple */
#ifndef MIN_VERSION_postgresql_simple
#define MIN_VERSION_postgresql_simple(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  7 || \
  (major1) == 0 && (major2) == 7 && (minor) <= 0)
#endif /* MIN_VERSION_postgresql_simple */
/* package random-1.2.1.3 */
#ifndef VERSION_random
#define VERSION_random "1.2.1.3"
#endif /* VERSION_random */
#ifndef MIN_VERSION_random
#define MIN_VERSION_random(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 1)
#endif /* MIN_VERSION_random */
/* package stm-2.5.3.1 */
#ifndef VERSION_stm
#define VERSION_stm "2.5.3.1"
#endif /* VERSION_stm */
#ifndef MIN_VERSION_stm
#define MIN_VERSION_stm(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  5 || \
  (major1) == 2 && (major2) == 5 && (minor) <= 3)
#endif /* MIN_VERSION_stm */
/* package text-2.1.3 */
#ifndef VERSION_text
#define VERSION_text "2.1.3"
#endif /* VERSION_text */
#ifndef MIN_VERSION_text
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  1 || \
  (major1) == 2 && (major2) == 1 && (minor) <= 3)
#endif /* MIN_VERSION_text */
/* package threepenny-gui-0.9.4.2 */
#ifndef VERSION_threepenny_gui
#define VERSION_threepenny_gui "0.9.4.2"
#endif /* VERSION_threepenny_gui */
#ifndef MIN_VERSION_threepenny_gui
#define MIN_VERSION_threepenny_gui(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  9 || \
  (major1) == 0 && (major2) == 9 && (minor) <= 4)
#endif /* MIN_VERSION_threepenny_gui */
/* package transformers-0.6.1.1 */
#ifndef VERSION_transformers
#define VERSION_transformers "0.6.1.1"
#endif /* VERSION_transformers */
#ifndef MIN_VERSION_transformers
#define MIN_VERSION_transformers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 1)
#endif /* MIN_VERSION_transformers */

/* tool gcc-14.0.6 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "14.0.6"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  14 || \
  (major1) == 14 && (major2) <  0 || \
  (major1) == 14 && (major2) == 0 && (minor) <= 6)
#endif /* MIN_TOOL_VERSION_gcc */
/* tool ghc-9.10.3 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "9.10.3"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  10 || \
  (major1) == 9 && (major2) == 10 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_ghc */
/* tool ghc-pkg-9.10.3 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "9.10.3"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  10 || \
  (major1) == 9 && (major2) == 10 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_ghc_pkg */
/* tool haddock-2.31.1 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.31.1"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  31 || \
  (major1) == 2 && (major2) == 31 && (minor) <= 1)
#endif /* MIN_TOOL_VERSION_haddock */
/* tool hpc-0.69 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.69"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  69 || \
  (major1) == 0 && (major2) == 69 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */
/* tool hsc2hs-0.68.10 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.10"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 10)
#endif /* MIN_TOOL_VERSION_hsc2hs */
/* tool runghc-9.10.3 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "9.10.3"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  10 || \
  (major1) == 9 && (major2) == 10 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_runghc */

#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "battleship-0.1.0-2SKVJUxErMaJqzjmpMLYOS-battleship-server"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.1.0"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
